name: mobile1_flutter_coding_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  dio: ^5.4.3+1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.4.7

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true