name: mobile1_flutter_coding_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0 
  shared_preferences: ^2.2.0
  dio: ^5.4.3+1
  intl: ^0.20.2
  auto_route: ^10.1.0+1
  get_it: ^8.0.3
  rxdart: ^0.28.0

  dartx: ^1.2.0 

  cupertino_icons: ^1.0.8  
  liquid_glass_renderer: ^0.1.1-dev.6
  
dev_dependencies: 
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^3.0.6
  auto_route_generator: ^10.1.0

  flutter_lints: ^6.0.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true